import type { Metadata } from "next";
import "./globals.css";
import { TanstackProvider } from "@/components/provider/tanstack-provider";


export const metadata: Metadata = {
  title: "CryptoTracker App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <TanstackProvider>
        {children}
        </TanstackProvider>
      </body>
    </html>
  );
}
